export interface MaskedProfile {
    user_id: string;
    full_name: string;
    avatar_url: string | null;
    nim: string;
    role: string | null;
    class_id?: string | null;
    whatsapp?: string | null;
    // Allow other properties to pass through
    [key: string]: any;
}

/**
 * Masks the profile data if the target user is an AdminDev and the current user is NOT an AdminDev.
 * @param targetProfile The profile to potentially mask.
 * @param currentUserRole The role of the currently logged-in user.
 * @returns The masked or original profile.
 */
export function getMaskedProfile(targetProfile: any, currentUserRole: string | null | undefined): MaskedProfile {
    if (!targetProfile) return targetProfile;

    const targetRole = (targetProfile.role || '').trim().toLowerCase();
    const currentRole = (currentUserRole || '').trim().toLowerCase();

    // IF target is AdminDev AND current user is NOT AdminDev -> MASK IT
    if (targetRole === 'admin_dev' && currentRole !== 'admin_dev') {
        return {
            ...targetProfile,
            full_name: 'Admin System',
            nim: '********', // Confidential
            avatar_url: null, // Initial "AD" will be generated by Fallback if url is null
            whatsapp: null, // Hide contact
            is_masked: true // Flag for UI to potentially show badges etc.
        };
    }

    return targetProfile;
}
